-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,SourceFile,LineNumberTable
-keep class com.nexo.tv.data.** { *; }
-keep class org.videolan.libvlc.** { *; }
-dontwarn org.videolan.libvlc.**
-keep class com.google.gson.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class androidx.security.crypto.** { *; }
